name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}}}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [22.3, 21.3]
        elixir: [1.10.3, 1.9.4, 1.8.2, 1.7.4, 1.6.6]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-mix-
    - uses: actions/cache@v1
      with:
        path: _build/ci
        key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
        restore-keys: |
          ${{ runner.os }}-build-
    - uses: actions/setup-elixir@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}

    - name: Install hex
      run: mix local.hex --force
    - name: Install rebar
      run: mix local.rebar --force
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
    - name: Report coverage
      run: mix coveralls.github
